@AutoTurn.Api_HostAddress = https://localhost:7131
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJnaXZlbl9uYW1lIjoic3RyaW5nIiwiZmFtaWx5X25hbWUiOiJzdHJpbmciLCJqdGkiOiIwNjJlY2E4Mi02MjFhLTRiOWYtOWVlYi1kN2JkNDdhYmUxMDQiLCJzdWIiOiIzZmQxOWM0Zi1jNWJkLTRmMWYtYTFjOS0yZGYwNzk4ZGVjZDciLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJTdXBlckFkbWluIiwiZXhwIjoxNzgxMDI4NjY4LCJpc3MiOiJhZG1pbiIsImF1ZCI6ImFkbWluIn0.TNJb72mxxmGcDAFADwOrAv6T_lfdkfZnz_fydFQtZ9E
@adminToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJnaXZlbl9uYW1lIjoiZnNkIiwiZmFtaWx5X25hbWUiOiJkZiIsImp0aSI6ImUwZmUzZTA5LTA1NWItNGI4MC04ZTVhLTE0NmQ2MjhiMTFmMCIsInN1YiI6Ijk2YTgwMDNkLTdmOTItNDlkMC1iMjY1LWZiYzZhMjZkNGQ1ZiIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzgxMDMxODQwLCJpc3MiOiJhZG1pbiIsImF1ZCI6ImFkbWluIn0.mPnTPO3TL3GMh1wIyzWbSGR1w0hzUfKKoE56ib2Dm_o
@normalToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJnaXZlbl9uYW1lIjoic3RyaW5nIiwiZmFtaWx5X25hbWUiOiJzdHJpbmciLCJqdGkiOiI0YTc4ZmMyOC0wMTc3LTRhZjQtYTlkMS00OTQ5Y2U4NWIxZGQiLCJzdWIiOiI3YzI1NjQxYi02ZDY5LTQ0ZmItOTI5MC04ZWExYzhkMGYzZDgiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJOb3JtYWwiLCJleHAiOjE3ODE0MDQwMjksImlzcyI6ImFkbWluIiwiYXVkIjoiYWRtaW4ifQ.O5EqYDBxLpnsfSpy_hYWN1YLyg0oZaxxXYnXL8MSllA

Post {{AutoTurn.Api_HostAddress}}/api/Turn 
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "foreignCode": "2321406099623136",
  "officeId": 151,
  "planId": 950,
  "foreignPhoneNumber": "fe"
}